import { StyleSheet, Dimensions } from "react-native";
import { themas } from "../../../global/themes";

export const style = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#000000',
  },
  boxTop: {
    height: Dimensions.get('window').height / 3,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  boxMid: {
    height: Dimensions.get('window').height / 4,
    width: '100%',
    paddingHorizontal: 37,
    justifyContent: 'center',
  },
  boxBottom: {
    height: Dimensions.get('window').height / 3,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingVertical: 20,
  },
  logo: {
    width: 80,
    height: 80,
    marginTop: 40,
    tintColor: '#FF0040',
    shadowColor: '#FF0040',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 20,
    elevation: 10,
  },
  appName: {
    fontSize: 48,
    fontWeight: '900',
    color: '#FF0040',
    marginTop: 20,
    marginBottom: 10,
    textShadowColor: '#FF0040',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 25,
    letterSpacing: 2,
  },
  text: {
    marginTop: 35,
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FF0040',
    textShadowColor: '#FF0040',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 15,
  },
  textBottom: {
    fontSize: 14,
    color: '#FF0040',
    marginTop: 25,
    textAlign: 'center',
    alignSelf: 'center',
    width: '100%',
    textShadowColor: '#FF0040',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  textBottomCreate: {
    fontSize: 16,
    color: '#FF0040',
    fontWeight: 'bold',
    textShadowColor: '#FF0040',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  textRecovery: {
    fontSize: 14,
    color: '#FF0040',
    textDecorationLine: 'underline',
    marginTop: 15,
    marginBottom: 15,
    fontWeight: '600',
    textShadowColor: '#FF0040',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#0A0A0A',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 30,
    paddingBottom: 40,
    borderTopWidth: 2,
    borderTopColor: '#FF0040',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FF0040',
    textShadowColor: '#FF0040',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 15,
  },
  modalSubtitle: {
    fontSize: 14,
    color: '#FF0040',
    marginBottom: 20,
    lineHeight: 20,
    opacity: 0.8,
  },
  modalInput: {
    borderWidth: 2,
    borderColor: '#FF0040',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    marginBottom: 20,
    color: '#FF0040',
    backgroundColor: '#1A1A1A',
  },
  modalButton: {
    marginBottom: 15,
  },
  modalCancel: {
    fontSize: 16,
    color: '#FF0040',
    textAlign: 'center',
    paddingVertical: 10,
    opacity: 0.7,
  },
  recoveryTypeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 20,
  },
  recoveryTypeButton: {
    flex: 1,
    paddingVertical: 12,
    marginHorizontal: 5,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#FF0040',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
  },
  recoveryTypeActive: {
    backgroundColor: '#FF0040',
    borderColor: '#FF0040',
    boxShadow: '0 0 20px #FF0040',
  },
  recoveryTypeText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FF0040',
  },
  recoveryTypeTextActive: {
    color: '#000000',
  },
  passwordInputContainer: {
    position: 'relative',
    marginBottom: 20,
  },
  passwordToggle: {
    position: 'absolute',
    right: 15,
    top: '50%',
    transform: [{ translateY: -10 }],
  },
});